# Generated by Django 4.2.7 on 2023-12-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='porjetos', max_length=100, verbose_name='projetos')),
                ('descricao', models.TextField(help_text='descricao do projeto', verbose_name='descricao do projeto')),
                ('tecnologia', models.CharField(help_text='django', max_length=20, verbose_name='django')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'db_table': 'projeto',
            },
        ),
    ]
